# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.srcs/sources_1/ip/rom_bkg/rom_bkg.xci
# IP: The module: 'rom_bkg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/rom_bkg/rom_bkg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bkg'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.srcs/sources_1/ip/rom_bkg/rom_bkg.xci
# IP: The module: 'rom_bkg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/rom_bkg/rom_bkg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_bkg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
