set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0/mb_block_microblaze_0_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0/mb_block_microblaze_0_0_in_context.xdc id:1 order:EARLY scoped_inst:mb_block_i/microblaze_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_v10_0/mb_usb_dlmb_v10_0/mb_block_dlmb_v10_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_v10_0/mb_usb_dlmb_v10_0/mb_block_dlmb_v10_0_in_context.xdc id:2 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/dlmb_v10} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_v10_0/mb_usb_ilmb_v10_0/mb_block_dlmb_v10_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_v10_0/mb_usb_ilmb_v10_0/mb_block_dlmb_v10_0_in_context.xdc id:3 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/ilmb_v10} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_0/mb_usb_dlmb_bram_if_cntlr_0/mb_block_dlmb_bram_if_cntlr_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_0/mb_usb_dlmb_bram_if_cntlr_0/mb_block_dlmb_bram_if_cntlr_0_in_context.xdc id:4 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_0/mb_usb_ilmb_bram_if_cntlr_0/mb_block_ilmb_bram_if_cntlr_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_0/mb_usb_ilmb_bram_if_cntlr_0/mb_block_ilmb_bram_if_cntlr_0_in_context.xdc id:5 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0_in_context.xdc id:6 order:EARLY scoped_inst:mb_block_i/microblaze_0_local_memory/lmb_bram} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0/mb_usb_xbar_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0/mb_usb_xbar_0_in_context.xdc id:7 order:EARLY scoped_inst:mb_block_i/microblaze_0_axi_periph/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0_in_context.xdc id:8 order:EARLY scoped_inst:mb_block_i/microblaze_0_axi_intc} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0/mb_block_mdm_1_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0/mb_block_mdm_1_0_in_context.xdc id:9 order:EARLY scoped_inst:mb_block_i/mdm_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0_in_context.xdc id:10 order:EARLY scoped_inst:mb_block_i/clk_wiz_1} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0/mb_block_rst_clk_wiz_1_100M_0_in_context.xdc id:11 order:EARLY scoped_inst:mb_block_i/rst_clk_wiz_1_100M} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0/mb_block_axi_uartlite_0_0_in_context.xdc id:12 order:EARLY scoped_inst:mb_block_i/axi_uartlite_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0_in_context.xdc id:13 order:EARLY scoped_inst:mb_block_i/gpio_usb_rst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0_in_context.xdc id:14 order:EARLY scoped_inst:mb_block_i/gpio_usb_int} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0_in_context.xdc id:15 order:EARLY scoped_inst:mb_block_i/gpio_usb_keycode} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0_in_context.xdc id:16 order:EARLY scoped_inst:mb_block_i/timer_usb_axi} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0/mb_usb_spi_usb_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0/mb_usb_spi_usb_0_in_context.xdc id:17 order:EARLY scoped_inst:mb_block_i/spi_usb} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/ip/ila_0/ila_0/ila_0_in_context.xdc id:18 order:EARLY scoped_inst:ila} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/hdmi_tx_0/hdmi_tx_0/hdmi_tx_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/ip/hdmi_tx_0/hdmi_tx_0/hdmi_tx_0_in_context.xdc id:19 order:EARLY scoped_inst:vga_to_hdmi} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:20 order:EARLY scoped_inst:clk_wiz} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.gen/sources_1/ip/bg_rom/bg_rom/bg_rom_in_context.xdc rfile:../../../../../laser_harp_test.gen/sources_1/ip/bg_rom/bg_rom/bg_rom_in_context.xdc id:21 order:EARLY scoped_inst:screen/background} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.srcs/constrs_1/imports/pin_assignment/mb_intro_top.xdc rfile:../../../../../laser_harp_test.srcs/constrs_1/imports/pin_assignment/mb_intro_top.xdc id:22} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc rfile:../../../../../laser_harp_test.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc id:23} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/estel/laser-harp-fpga/laser_harp_test/laser_harp_test.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:24} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0/Clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 33.333 [get_pins mb_block_i/microblaze_0/Dbg_Clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 33.333 [get_pins mb_block_i/microblaze_0/Dbg_Update]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_v10/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_v10/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/BRAM_Clk_A]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr/LMB_Clk]
set_property src_info {type:SCOPED_XDC file:5 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/microblaze_0_local_memory/lmb_bram/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/microblaze_0_local_memory/lmb_bram/clkb]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_axi_periph/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/microblaze_0_axi_intc/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/microblaze_0_axi_intc]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name mb_block_i/mdm_1/Dbg_Update_0 [get_pins mb_block_i/mdm_1/Dbg_Update_0]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 33.333 -name mb_block_i/mdm_1/Dbg_Clk_0 [get_pins mb_block_i/mdm_1/Dbg_Clk_0]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/mdm_1]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name Clk [get_ports Clk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mb_block_i/clk_wiz_1/clk_out1 -source [get_pins mb_block_i/clk_wiz_1/clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins mb_block_i/clk_wiz_1/clk_out1]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/clk_wiz_1]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/rst_clk_wiz_1_100M/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/rst_clk_wiz_1_100M]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/axi_uartlite_0/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/axi_uartlite_0]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_usb_rst/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_usb_rst]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_usb_int/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_usb_int]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/gpio_usb_keycode/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/gpio_usb_keycode]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mb_block_i/timer_usb_axi/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/timer_usb_axi]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/spi_usb/ext_spi_clk]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins mb_block_i/spi_usb/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:17 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mb_block_i/spi_usb]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ila/clk]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ila]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports hdmi_tmds_clk_n]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports hdmi_tmds_clk_n]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports hdmi_tmds_clk_p]
set_property src_info {type:SCOPED_XDC file:19 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports hdmi_tmds_clk_p]
set_property src_info {type:SCOPED_XDC file:19 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_n[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[0]}]
set_property src_info {type:SCOPED_XDC file:19 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[1]}]
set_property src_info {type:SCOPED_XDC file:19 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {hdmi_tmds_data_p[2]}]
set_property src_info {type:SCOPED_XDC file:19 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells vga_to_hdmi]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name Clk [get_ports Clk]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_wiz/clk_out1 -source [get_pins clk_wiz/clk_in1] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_pins clk_wiz/clk_out1]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_wiz/clk_out2 -source [get_pins clk_wiz/clk_in1] -edges {1 2 3} -edge_shift {0.000 -1.000 -2.000} [get_pins clk_wiz/clk_out2]
set_property src_info {type:SCOPED_XDC file:20 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports Clk]
set_property src_info {type:SCOPED_XDC file:20 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports Clk]
set_property src_info {type:SCOPED_XDC file:20 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_wiz]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins screen/background/clka]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells screen/background]
set_property src_info {type:XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]
set_property src_info {type:XDC file:23 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property src_info {type:XDC file:23 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property src_info {type:XDC file:23 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property src_info {type:XDC file:23 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property src_info {type:XDC file:23 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property src_info {type:XDC file:23 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property src_info {type:XDC file:23 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property src_info {type:XDC file:23 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property src_info {type:XDC file:23 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property src_info {type:XDC file:23 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]
set_property src_info {type:XDC file:23 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[3]}]
set_property src_info {type:XDC file:23 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[2]}]
set_property src_info {type:XDC file:23 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[1]}]
set_property src_info {type:XDC file:23 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridA[0]}]
set_property src_info {type:XDC file:23 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[3]}]
set_property src_info {type:XDC file:23 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[2]}]
set_property src_info {type:XDC file:23 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[1]}]
set_property src_info {type:XDC file:23 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_gridB[0]}]
set_property src_info {type:XDC file:23 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[7]}]
set_property src_info {type:XDC file:23 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[6]}]
set_property src_info {type:XDC file:23 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[5]}]
set_property src_info {type:XDC file:23 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[4]}]
set_property src_info {type:XDC file:23 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[3]}]
set_property src_info {type:XDC file:23 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[2]}]
set_property src_info {type:XDC file:23 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[1]}]
set_property src_info {type:XDC file:23 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segA[0]}]
set_property src_info {type:XDC file:23 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[7]}]
set_property src_info {type:XDC file:23 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[6]}]
set_property src_info {type:XDC file:23 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[5]}]
set_property src_info {type:XDC file:23 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[4]}]
set_property src_info {type:XDC file:23 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[3]}]
set_property src_info {type:XDC file:23 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[2]}]
set_property src_info {type:XDC file:23 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[1]}]
set_property src_info {type:XDC file:23 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_segB[0]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/dlmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/ilmb_v10]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/dlmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/ilmb_bram_if_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_local_memory/lmb_bram]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_periph/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_periph]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/microblaze_0_axi_intc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/mdm_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/clk_wiz_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/rst_clk_wiz_1_100M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/axi_uartlite_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_usb_rst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_usb_int]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/gpio_usb_keycode]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/timer_usb_axi]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/spi_usb]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mb_block_i/xlconcat_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells ila]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells vga_to_hdmi]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells clk_wiz]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells screen/background]
